name: Docker Image CI

on:
  push:
    branches: [ "features" ]
  pull_request:
    branches: [ "features" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image:1.0.0-$(date +%s)
        docker images
